language: node_js
node_js: 5.5.0
os:
  - linux
  - osx
install:
  - npm install
env:
  global:
    secure: EgSICeeGjIo+/7jKESTRhEhsK6toKdxvKRuY7ddo5S11mz8kg+UT3bzDoyJ2JJ9NywkdH1wds3aJr1I/vNovPulKgYMskpJPh0UbY+PSdiGg9iViYEpGVsA9Rh6jpdmYC0dHHBvEqNXQ/UFmhOjZnVpyrxPA0qawB7MI8swTU3At3vypxBA42BnIafw7ugns9UXz6ZeInxre36lycNXr9PnZ0p2qj1Lr47g+L/QYQRlbdZ8EDuZZLEksBpp7tL1psc7B+eUyucoT8CJgMwVOw2BPDum9g0QFOSOQU3Baciy+sfEjUP9rof1lMxrRPFqHWQHGOuqdfEHHoot2t6FV/a8z1Hbbkk1EonnVizZ3DAJX1ePhkwrxwz9PWgZbQtaOSv/563O6EVeeL4QIc25GV70/JNNqQUm6Qca0re0n8fpk2DPlKx6lCJJhkDt7vkgZOE0PVoE9smlmwERUsWTdXaBnSyUDTQI8bhuL1OQ781asPkYS0Kx2kLf8xssehfCcAVG6CkmKzNVpX0n8sLZM4igwFcNP4AQXQ5G6Kg0f1l0l8TiK3X0PSA8YmAT22fEpZhOGj/QO4qBVg0e9789P9hvWNhm3kfLhHiGWHBmFAIpqGyg38E6aYxGV/fce5WT4ZT0AsSA2lbKJqPtzAHWTPCubNoYT9TLxIEBskbUqGjc=
